Second homework
VladWolf/OT pull request #2
Opened 2022-11-30 18:06 UTC by VladWolf

чекаю розгром

2022-11-30 18:14 UTC, VladWolf commented
Підскажіть будь ласка чи це нормально, що тут показує комміти до останнього пул реквесту ? Чи я можу/мені треба це якось почистити?

2022-12-01 23:21 UTC, shorodilov commented
> Підскажіть будь ласка чи це нормально, що тут показує комміти попереднього пул реквесту ? Чи я можу/мені треба це якось почистити?

Нормально

2022-12-02 12:13 UTC, shorodilov requested changes
Загалом добре.
Треба дещо підправити маленько і можна бути зливати до основної гілки.

2022-12-02 12:13 UTC, shorodilov commented on shop.py
> +        return self.name == other.name and self.price == other.price
Треба перебчати поведінку для ситуації, коли порівняння відбувається з обʼєктом іншого типу.
Наприклад: ```product_obj == "product"```

2022-12-02 12:13 UTC, shorodilov commented on shop.py
> +        return new_obj
Не вірний рівень ідентації
```suggestion
            return new_obj
```

2022-12-02 12:13 UTC, shorodilov commented on shop.py
> +    def __init__(self, name='', price=''):
Нащо тут значення за замовчуванням?

2022-12-02 12:24 UTC, VladWolf commented on shop.py
> +    def __init__(self, name='', price=''):
ви в своїх прикладах створювали продукти змінюючи атрибути обєкта, а не передевали їх відразу
apple = Product() такий запис без значень за замовчуванням веде до помилки, тому вирішив зробити так
apple.name = "apple"
apple.price = 10.59

2022-12-02 12:42 UTC, VladWolf commented
Ну думаю, що так норм. Взагалі там в __eq__ можно ще додати перевірку типу напевно на float, int і рівняти з ціною, але я думаю цього теж достатньо напевно)

2022-12-02 12:54 UTC, shorodilov commented on shop.py
> +    def __init__(self, name='', price=''):
Зрозумів.
Тут треба памʼятати, що у мене приклади ідуть за наростаючою.
Той що ти навів - він до реалізації ``__init__``

2022-12-02 12:57 UTC, shorodilov requested changes
Треба прибрати значення за замовчуванням з `Product.__init__`.
Треба внести невеличкі зміни до `Product.__eq__`.

2022-12-02 12:57 UTC, shorodilov commented on shop.py
> +            return self.name == other
```suggestion
            return False
```

2022-12-02 12:58 UTC, shorodilov commented
> Ну думаю, що так норм. Взагалі там в **eq** можно ще додати перевірку типу напевно на float, int і рівняти з ціною, але я думаю цього теж достатньо напевно)

Та не треба. Просто порівняння з обʼєктом іншого типу - False і годі.

2022-12-02 13:08 UTC, VladWolf commented
Implement both Product and ShoppingCart initializers to provide required data while creating instances. It's ok to initialize empty carts. У вас ще таке було в завданні. Я думав в __init__ додати print(f"Product name: {name}, product price {price}") ну або якось через __str__ гарніше, чи це я так зрозумів. В загальному все інше напевно вже виглядає норм.

2022-12-02 19:21 UTC, shorodilov approved these changes
lgtm

2022-12-02 21:10 UTC, merged