l_30-31
VladWolf/OT pull request #7
Opened 2023-02-03 00:55 UTC by VladWolf

2023-02-03 00:57 UTC, VladWolf commented
Підскажіть, а чи можу я заносити в базу по цифрі, а коли я хочу бачити відображення, то мені буде показувати саме текст? Чи не паритись і залишити просто вибори категорій без цифр?

2023-02-03 01:31 UTC, shorodilov commented
> Підскажіть, а чи можу я заносити в базу по цифрі, а коли я хочу бачити відображення, то мені буде показувати саме текст? Чи не паритись і залишити просто вибори категорій без цифр?

https://docs.djangoproject.com/en/4.1/ref/models/fields/#choices

2023-02-03 02:19 UTC, VladWolf commented
> > Підскажіть, а чи можу я заносити в базу по цифрі, а коли я хочу бачити відображення, то мені буде показувати саме текст? Чи не паритись і залишити просто вибори категорій без цифр?
> 
> https://docs.djangoproject.com/en/4.1/ref/models/fields/#choices

Я знаю про документацію), але ці варіанти не спрацювали в тасках все одно пише цифру

2023-02-03 02:44 UTC, VladWolf commented
> > Підскажіть, а чи можу я заносити в базу по цифрі, а коли я хочу бачити відображення, то мені буде показувати саме текст? Чи не паритись і залишити просто вибори категорій без цифр?
> 
> https://docs.djangoproject.com/en/4.1/ref/models/fields/#choices

Можливо ви мене не до кінця зрозуміли, але воно відображає текст тільки у адмінці, а на сторінці тасків все одно цифра. Я спробував ці штуки з choices, але результат був однаковий.

2023-02-03 03:04 UTC, shorodilov commented
> > > Підскажіть, а чи можу я заносити в базу по цифрі, а коли я хочу бачити відображення, то мені буде показувати саме текст? Чи не паритись і залишити просто вибори категорій без цифр?
> > 
> > 
> > https://docs.djangoproject.com/en/4.1/ref/models/fields/#choices
> 
> Можливо ви мене не до кінця зрозуміли, але воно відображає текст тільки у адмінці, а на сторінці тасків все одно цифра. Я спробував ці штуки з choices, але результат був однаковий.

А додай картинку. Бо так поки не зрозуміло...

2023-02-03 11:49 UTC, VladWolf commented
> > > > Підскажіть, а чи можу я заносити в базу по цифрі, а коли я хочу бачити відображення, то мені буде показувати саме текст? Чи не паритись і залишити просто вибори категорій без цифр?
> > > 
> > > 
> > > https://docs.djangoproject.com/en/4.1/ref/models/fields/#choices
> > 
> > 
> > Можливо ви мене не до кінця зрозуміли, але воно відображає текст тільки у адмінці, а на сторінці тасків все одно цифра. Я спробував ці штуки з choices, але результат був однаковий.
> 
> А додай картинку. Бо так поки не зрозуміло...

![image](https://user-images.githubusercontent.com/117385238/216596198-cd2a2454-f8b7-4398-b6e0-bebc7627079c.png)
![image](https://user-images.githubusercontent.com/117385238/216596237-1fd16d3e-0715-4344-b121-9cd1add71fbb.png)

2023-02-08 02:41 UTC, VladWolf commented
короче знайшов, що те, що я хотів можна було зробити з get_'choices_name'_display()

2023-02-08 02:43 UTC, VladWolf commented
По завданню здається це все, що треба було зробити, можу зливати?

2023-02-08 17:15 UTC, shorodilov requested changes
Зроби категорію через зв'язану модель.
У іншому - нормально.

2023-02-08 17:15 UTC, shorodilov commented on jdjango/pydjango/task/models.py
> +        (1, "No Category"),
Зроби окремою моделю, бо задовбаєшся їх міняти у коді.
Зв'язок `1-to-N` або `N-to-N` в залежності від того, скільки категорій бажаєш мати для одно `task` - одну чи декілька.

2023-02-13 11:01 UTC, shorodilov approved these changes
lgtm

2023-02-14 10:45 UTC, merged